# Generated by Django 5.2.1 on 2025-05-24 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 24, 1, 23, 8, 942977, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Administrator')], default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.BooleanField(default=False),
        ),
    ]
