# Generated by Django 5.2.1 on 2025-05-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usernotverified_remove_customuser_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.BooleanField(default=False),
        ),
    ]
